#!/bin/bash
# @author: Vishal Verma
# @date: 05/16/18
# Keep this file in home/<user>/bin dir
# Backward jump capabilty
# This script add feature to bj script for autocompletion
# file: /bin/_bj

#declare function to pass to `complete'
_bj()
{
    # declare variable `cur' (holds string to complete) as local
    local cur

    # initialize completion (abort on fail)
    _init_completion || return
    
		OLDIFS=$IFS #Internal field seperator
		IFS=/
		CURR=($PWD)
		IFS=$OLDIFS
		echo
		echo ${CURR[@]}

# if declaring the function was successful, use it when the command is `myscript'
} && complete -F _bj bj
