#!/bin/bash
# @author: Vishal Verma
# @date: 05/16/18
# Keep this file in home/<user>/bin dir
# Backward jump capabilty
# file: /bin/bj

if [[ ( $# -ne 1 ) || ( -z $1 ) ]]; then
    echo "Usage: jmp <directory name >"
	echo "directory you want to jump back"
	return
fi

OLDIFS=$IFS #Internal field seperator
IFS=/
DIR=$1
TEMP=`pwd`
CURR=($PWD)
IFS=$OLDIFS

if [[ ("$DIR" == "/") || ("$DIR" == "..") ]]; then
	cd $DIR
else

	for i in "${CURR[@]}"
	do
		if [[ "$i" == "$DIR" ]]; then
			NEXT+="$i"
			break	
		else
			NEXT+="$i/"
		fi
	done

	if [[ "$NEXT" == "$TEMP/" ]]; then
		echo "$DIR : No such directory found"
	else
		cd $NEXT
	fi

fi
unset NEXT
unset CURR
unset TEMP
unset i
unset DIR
