#!/bin/bash
# @author: Vishal Verma
# @date: 05/16/18
# Keep this file in home/<user>/bin dir
# file: /bin/master-alias

alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
alias c='clear'
alias bj='. bj'
alias fj='. fj'
source ~/bin/_bj