#!/bin/bash
# @author: Vishal Verma
# @date: 05/16/18
# Keep this file in home/<user>/bin dir
# file: /bin/updprj


echo "Updating all projects...."
cd /home/vvverma/projects; \
for d in ./*/
do
echo "UPDATING PROJECT $d"
cd  "$d"
repo sync
echo "PROJECT "$d" UPDATED"
cd ..
done

echo "Finished updating all projects...."
